macro(FetchContent_MakeAvailable NAME)
    FetchContent_GetProperties(${NAME})
    string(TOLOWER "${NAME}" lcName)
    message( STATUS "Fetch: ${NAME}")
    if(NOT ${lcName}_POPULATED)
        FetchContent_Populate(${NAME})
        message( STATUS "Dirs: ${${lcName}_SOURCE_DIR} ${${lcName}_BINARY_DIR}")
        add_subdirectory(${${lcName}_SOURCE_DIR} ${${lcName}_BINARY_DIR})
    endif()
endmacro()
